chore : Migrate CI to GitHub Actions
fabric8-analytics/fabric8-analytics-data-model pull request #351
Opened 2020-10-29 07:17 UTC by sawood14012

# Description

Have added/updated scripts which enable git hub actions .

- [X] New feature (non-breaking change which adds functionality)

2021-01-05 16:57 UTC, sawood14012 commented on cico_run_pylint.sh
> -./qa/measure-cyclomatic-complexity.sh
removed cc check in linter because unit tests script runs it

2021-01-05 17:31 UTC, arajkumar requested changes

2021-01-05 17:31 UTC, arajkumar commented on requirements.in
> +psycopg2==2.7.6.1
Use psycopg2-binary without version locking.

2021-01-05 17:31 UTC, arajkumar commented on requirements.in
> +minio==4.0.8
Don't version lock on requirement.in unless otherwise needed

2021-01-05 18:18 UTC, sawood14012 commented on requirements.in
> +minio==4.0.8
i have only version locked if the newer versions cause problems

2021-01-05 18:18 UTC, sawood14012 commented on requirements.in
> +psycopg2==2.7.6.1
okay

2021-01-06 05:47 UTC, arajkumar requested changes

2021-01-06 05:47 UTC, arajkumar commented on cico_run_pylint.sh
>  #./measure-cyclomatic-complexity.sh --fail-on-error
Don't comment, delete it if you don't need it.

2021-01-06 05:47 UTC, arajkumar commented on requirements.in
> +mock
I see both normal and dev dependencies in the same file. Are you doing dependency cleanup as part of this work? In that case it has to be split into 2.

2021-01-06 07:57 UTC, sawood14012 commented on cico_run_pylint.sh
>  #./measure-cyclomatic-complexity.sh --fail-on-error
done

2021-01-06 07:57 UTC, sawood14012 commented on requirements.in
> +mock
done

2021-01-06 09:29 UTC, arajkumar requested changes

2021-01-06 09:29 UTC, arajkumar commented on requirements.in
> +minio==4.0.8
Isn't minio a test dependency?

2021-01-06 09:29 UTC, arajkumar commented on requirements.in
> +werkzeug==0.16.0
Why this is version locked? None of our repos lock werkzeug.

2021-01-06 09:29 UTC, arajkumar commented on qa/runtests.sh
> +    pip install -r test/requirements.txt
Do a atomic install.
```suggestion
    pip install -r requirements.txt -r test/requirements.txt
```

2021-01-06 09:46 UTC, sawood14012 commented on requirements.in
> +werkzeug==0.16.0
werkzeug has a newer versions eg: 1.0.0 but the package we use has been moved , if we dont version lock  werkzeug then we have to change some of the code 
ref :  `src/rest_api.py:388
  /Users/sawood/work/fabric8-analytics-data-model/src/rest_api.py:388: DeprecationWarning: 'werkzeug.contrib.fixers.ProxyFix' has moved to 'werkzeug.middleware.proxy_fix.ProxyFix'. This import is deprecated as of version 0.15 and will be removed in 1.0.
    app.wsgi_app = ProxyFix(app.wsgi_app)`

2021-01-06 09:47 UTC, sawood14012 commented on requirements.in
> +minio==4.0.8
yup

2021-01-27 12:11 UTC, sawood14012 commented
[test]

2021-01-27 13:48 UTC, arajkumar approved these changes
lgtm

2021-03-01 07:47 UTC, sawood14012 commented
[test]

2021-03-02 03:38 UTC, merged