Batch processing for edge creation for vulnerabilities
fabric8-analytics/fabric8-analytics-data-model pull request #353
Opened 2020-12-29 10:27 UTC by yzainee

Changed the logic from sequential creation of edges between vuln and version node to batch processing

2020-12-29 11:05 UTC, yzainee commented
[test]

2020-12-29 12:18 UTC, arajkumar requested changes

2020-12-29 12:18 UTC, arajkumar commented on src/cve.py
>                                  call_gremlin(self.prepare_payload
Can this be split into separate function for batch processing?
Similar to https://github.com/fabric8-analytics/f8a-server-backbone/blob/master/src/v2/stack_aggregator.py#L123:5?

2021-01-04 07:51 UTC, yzainee commented
[test]

2021-01-04 12:53 UTC, arajkumar approved these changes
lgtm

2021-01-04 13:07 UTC, merged