Move to app-sre
fabric8-analytics/fabric8-analytics-data-model pull request #364
Opened 2021-03-25 12:48 UTC by yzainee

files added to support movement to app-sre cd

2021-03-25 12:57 UTC, arajkumar requested changes

2021-03-25 12:57 UTC, arajkumar commented on Dockerfile.app-sre
> +RUN pip3 install --upgrade pip --no-cache-dir
You need to repeat `--no-cache-dir` whereever you do `pip install`

2021-03-25 12:57 UTC, arajkumar commented on Dockerfile.app-sre
> +RUN pip3 install git+https://github.com/fabric8-analytics/fabric8-analytics-utils.git@6cb0a2d
Didn't we streamlined depenedency installation for data-model?
CC: @sawood14012

2021-03-25 12:57 UTC, arajkumar commented on build_deploy.sh
> +              -f ./Dockerfile .
use Dockerfile.app-sre here
```suggestion
              -f ./Dockerfile.app-sre .
```

2021-03-25 12:57 UTC, arajkumar commented on openshift/template.app-sre.yaml
> +apiVersion: v1
This is not needed incase we are using UBI image, you can use existing template.

2021-03-25 13:09 UTC, sawood14012 commented on Dockerfile.app-sre
> +RUN pip3 install git+https://github.com/fabric8-analytics/fabric8-analytics-utils.git@6cb0a2d
we might need to upgrade pip , @yzainee you can use `pip3 install -r requirements.txt ` or for test requirements `pip3 install -r requirements.txt -r test/requirements.txt` no need to explicitly install utils its already present in the requirements file

2021-03-25 13:40 UTC, yzainee commented on build_deploy.sh
> +              -f ./Dockerfile .
typo. rectified

2021-03-25 13:43 UTC, yzainee commented on openshift/template.app-sre.yaml
> +apiVersion: v1
i have checked in api server: https://github.com/fabric8-analytics/fabric8-analytics-server/blob/master/openshift/template.yaml Please cross check

2021-03-25 13:44 UTC, yzainee commented on Dockerfile.app-sre
> +RUN pip3 install --upgrade pip --no-cache-dir
done

2021-03-25 14:00 UTC, arajkumar commented on openshift/template.app-sre.yaml
> +apiVersion: v1
No, not required. I don't know why @rafiu007 did that.

2021-03-25 14:06 UTC, rafiu007 commented on openshift/template.app-sre.yaml
> +apiVersion: v1
@arajkumar  did not make any changes in the openshift /api-server template rekated to app-sre switch.

2021-03-25 14:13 UTC, yzainee commented on openshift/template.app-sre.yaml
> +apiVersion: v1
@arajkumar you have any sample which is running properly without that?

2021-03-25 14:16 UTC, arajkumar commented on openshift/template.app-sre.yaml
> +apiVersion: v1
I'm not sure whether I understand your question, but the existing template.yaml will work. Don't add this.

2021-03-25 14:20 UTC, yzainee commented on openshift/template.app-sre.yaml
> +apiVersion: v1
ok so it will pick the existing file itself. no need to add this new file then?

2021-03-25 14:48 UTC, yzainee commented on openshift/template.app-sre.yaml
> +apiVersion: v1
file removed

2021-03-25 14:48 UTC, yzainee commented on Dockerfile.app-sre
> +RUN pip3 install git+https://github.com/fabric8-analytics/fabric8-analytics-utils.git@6cb0a2d
done

2021-03-29 06:29 UTC, arajkumar approved these changes
> ADD ./ /tmp/f8a_data_model/
> ..
> RUN cd /tmp/f8a_data_model && pip3 install . --no-cache-dir

Though I've some concerns regarding the above step, it shall be fixed in a separate PR as I see similar pattern in existing Dockerfile as well.

lgtm

2021-03-29 06:33 UTC, merged